#if !canImport(ObjectiveC)
import XCTest

extension cpuTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__cpuTests = [
        ("testAVX2", testAVX2),
        ("testAVX", testAVX),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(cpuTests.__allTests__cpuTests),
    ]
}
#endif
